# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoScrollBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 345)
        self.horizontalScrollBarSugarLevel = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugarLevel.setGeometry(QtCore.QRect(180, 30, 160, 16))
        self.horizontalScrollBarSugarLevel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugarLevel.setObjectName("horizontalScrollBarSugarLevel")
        self.verticalScrollBarPulseRate = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarPulseRate.setGeometry(QtCore.QRect(100, 110, 16, 160))
        self.verticalScrollBarPulseRate.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarPulseRate.setObjectName("verticalScrollBarPulseRate")
        self.labelSugarLevel = QtWidgets.QLabel(Dialog)
        self.labelSugarLevel.setGeometry(QtCore.QRect(20, 20, 81, 18))
        self.labelSugarLevel.setObjectName("labelSugarLevel")
        self.labelBloodPressure = QtWidgets.QLabel(Dialog)
        self.labelBloodPressure.setGeometry(QtCore.QRect(20, 50, 111, 18))
        self.labelBloodPressure.setObjectName("labelBloodPressure")
        self.labelPulseRate = QtWidgets.QLabel(Dialog)
        self.labelPulseRate.setGeometry(QtCore.QRect(20, 80, 81, 18))
        self.labelPulseRate.setObjectName("labelPulseRate")
        self.horizontalSliderBloodPressure = QtWidgets.QSlider(Dialog)
        self.horizontalSliderBloodPressure.setGeometry(QtCore.QRect(180, 60, 160, 20))
        self.horizontalSliderBloodPressure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBloodPressure.setObjectName("horizontalSliderBloodPressure")
        self.verticalSliderCholestrolLevel = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholestrolLevel.setGeometry(QtCore.QRect(320, 110, 20, 160))
        self.verticalSliderCholestrolLevel.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholestrolLevel.setObjectName("verticalSliderCholestrolLevel")
        self.labelCholestrolLevel = QtWidgets.QLabel(Dialog)
        self.labelCholestrolLevel.setGeometry(QtCore.QRect(190, 110, 111, 18))
        self.labelCholestrolLevel.setObjectName("labelCholestrolLevel")
        self.lineEditResult = QtWidgets.QLineEdit(Dialog)
        self.lineEditResult.setGeometry(QtCore.QRect(30, 290, 301, 32))
        self.lineEditResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditResult.setObjectName("lineEditResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSugarLevel.setText(_translate("Dialog", "Sugar Level"))
        self.labelBloodPressure.setText(_translate("Dialog", "Blood Pressure"))
        self.labelPulseRate.setText(_translate("Dialog", "Pulse Rate"))
        self.labelCholestrolLevel.setText(_translate("Dialog", "Cholestrol Level"))
