# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSpinner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 219)
        self.labelBookPrice = QtWidgets.QLabel(Dialog)
        self.labelBookPrice.setGeometry(QtCore.QRect(30, 40, 81, 18))
        self.labelBookPrice.setObjectName("labelBookPrice")
        self.labelSugarPrice = QtWidgets.QLabel(Dialog)
        self.labelSugarPrice.setGeometry(QtCore.QRect(30, 90, 81, 18))
        self.labelSugarPrice.setObjectName("labelSugarPrice")
        self.lineEditBookPrice = QtWidgets.QLineEdit(Dialog)
        self.lineEditBookPrice.setGeometry(QtCore.QRect(130, 30, 113, 32))
        self.lineEditBookPrice.setObjectName("lineEditBookPrice")
        self.lineEditSugarPrice = QtWidgets.QLineEdit(Dialog)
        self.lineEditSugarPrice.setGeometry(QtCore.QRect(130, 80, 113, 32))
        self.lineEditSugarPrice.setObjectName("lineEditSugarPrice")
        self.lineEditBookAmount = QtWidgets.QLineEdit(Dialog)
        self.lineEditBookAmount.setGeometry(QtCore.QRect(400, 30, 113, 32))
        self.lineEditBookAmount.setObjectName("lineEditBookAmount")
        self.lineEditSugarAmount = QtWidgets.QLineEdit(Dialog)
        self.lineEditSugarAmount.setGeometry(QtCore.QRect(400, 80, 113, 32))
        self.lineEditSugarAmount.setObjectName("lineEditSugarAmount")
        self.spinBoxBookQty = QtWidgets.QSpinBox(Dialog)
        self.spinBoxBookQty.setGeometry(QtCore.QRect(300, 30, 52, 32))
        self.spinBoxBookQty.setObjectName("spinBoxBookQty")
        self.doubleSpinBoxSugarWeight = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxSugarWeight.setGeometry(QtCore.QRect(280, 80, 71, 32))
        self.doubleSpinBoxSugarWeight.setObjectName("doubleSpinBoxSugarWeight")
        self.labelTotalAmount = QtWidgets.QLabel(Dialog)
        self.labelTotalAmount.setGeometry(QtCore.QRect(410, 150, 101, 18))
        self.labelTotalAmount.setText("")
        self.labelTotalAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTotalAmount.setObjectName("labelTotalAmount")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelBookPrice.setText(_translate("Dialog", "Book Price"))
        self.labelSugarPrice.setText(_translate("Dialog", "Sugar Price"))
