# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCheckBox2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(638, 408)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 10, 41, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 131, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 111, 18))
        self.label_3.setObjectName("label_3")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(30, 360, 571, 18))
        self.labelAmount.setText("")
        self.labelAmount.setObjectName("labelAmount")
        self.groupBoxIceCreams = QtWidgets.QGroupBox(Dialog)
        self.groupBoxIceCreams.setGeometry(QtCore.QRect(180, 40, 261, 131))
        self.groupBoxIceCreams.setObjectName("groupBoxIceCreams")
        self.checkBoxChocolateChips = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxChocolateChips.setGeometry(QtCore.QRect(10, 30, 191, 24))
        self.checkBoxChocolateChips.setObjectName("checkBoxChocolateChips")
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxCookieDough.setGeometry(QtCore.QRect(10, 50, 141, 24))
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.checkBoxChocolateAlmond = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxChocolateAlmond.setGeometry(QtCore.QRect(10, 70, 161, 24))
        self.checkBoxChocolateAlmond.setObjectName("checkBoxChocolateAlmond")
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.groupBoxIceCreams)
        self.checkBoxRockyRoad.setGeometry(QtCore.QRect(10, 90, 121, 24))
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.groupBoxDrinks = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(180, 190, 261, 111))
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.checkBoxCoffe = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxCoffe.setGeometry(QtCore.QRect(10, 30, 85, 24))
        self.checkBoxCoffe.setObjectName("checkBoxCoffe")
        self.checkBoxSoda = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxSoda.setGeometry(QtCore.QRect(10, 50, 85, 24))
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.checkBoxTea = QtWidgets.QCheckBox(self.groupBoxDrinks)
        self.checkBoxTea.setGeometry(QtCore.QRect(10, 70, 71, 24))
        self.checkBoxTea.setObjectName("checkBoxTea")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Menu"))
        self.label_2.setText(_translate("Dialog", "Select your IceCream"))
        self.label_3.setText(_translate("Dialog", "Select your Drink"))
        self.groupBoxIceCreams.setTitle(_translate("Dialog", "IceCream"))
        self.checkBoxChocolateChips.setText(_translate("Dialog", "Mint Chocolate Chips $ 4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "Cookie Dough $ 2"))
        self.checkBoxChocolateAlmond.setText(_translate("Dialog", "Chocolate Almond $ 3"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "Rocky Road $ 5"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "Drinks"))
        self.checkBoxCoffe.setText(_translate("Dialog", "Coffe $ 2"))
        self.checkBoxSoda.setText(_translate("Dialog", "Soda $ 3"))
        self.checkBoxTea.setText(_translate("Dialog", "Tea $ 1"))
